[package]
name = "cambia-codegen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codegen = "0.2.0"
regex = "1"
walkdir = "2"
simple-text-decode = { path = "../simple-text-decode" }
sha2 = "0.10.6"
hex = "0.4.3"
scraper = "0.20.0"
reqwest = { version = "0.12.7", features = ["blocking"] }
accuraterip-drive-db = { path = "../accuraterip-drive-db" }
itertools = "0.13.0"
