// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccurateRipConfidence } from "./AccurateRipConfidence";
import type { AccurateRipStatus } from "./AccurateRipStatus";

export interface AccurateRipUnit { version: number | null, sign: string, offset_sign: string, confidence: AccurateRipConfidence | null, status: AccurateRipStatus, }