// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccurateRipConfidence } from "./AccurateRipConfidence";

export interface AccurateRipInfo { v1_sign: string, v2_sign: string, confidence: AccurateRipConfidence, }