// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccurateRipConfidenceTotal } from "./AccurateRipConfidenceTotal";
import type { AccurateRipOffset } from "./AccurateRipOffset";

export interface AccurateRipConfidence { matching: number | null, total: AccurateRipConfidenceTotal | null, offset: AccurateRipOffset, }