// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationCombined } from "./EvaluationCombined";
import type { ParsedLogCombined } from "./ParsedLogCombined";

export interface CambiaResponse { id: Array<number>, parsed: ParsedLogCombined, evaluation_combined: Array<EvaluationCombined>, }