// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Integrity } from "./Integrity";

export interface Checksum { log: string, calculated: string, integrity: Integrity, }