// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeductionCategory } from "./DeductionCategory";
import type { DeductionField } from "./DeductionField";

export interface DeductionData { category: DeductionCategory, field: DeductionField, message: string, }