// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeductionData } from "./DeductionData";

export interface Deduction { deduction_score: string, data: DeductionData, }