// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evaluation } from "./Evaluation";
import type { EvaluatorType } from "./EvaluatorType";

export interface EvaluationCombined { evaluator: EvaluatorType, combined_score: string, evaluations: Array<Evaluation>, }