// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationUnitCategory } from "./EvaluationUnitCategory";
import type { EvaluationUnitField } from "./EvaluationUnitField";

export interface EvaluationUnitData { category: EvaluationUnitCategory, field: EvaluationUnitField, message: string, }