// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationUnitData } from "./EvaluationUnitData";

export interface EvaluationUnit { unit_score: string, data: EvaluationUnitData, }