// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationUnitClass } from "./EvaluationUnitClass";
import type { EvaluationUnitField } from "./EvaluationUnitField";
import type { EvaluationUnitScope } from "./EvaluationUnitScope";

export interface EvaluationUnitData { scope: EvaluationUnitScope, field: EvaluationUnitField, message: string, class: EvaluationUnitClass, }