// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Gap = "Append" | "AppendNoHtoa" | "AppendUndetected" | "Prepend" | "Discard" | "Unknown" | "Inapplicable";