import type { Component } from 'svelte';

/**
 * An icon component — either one generated by unplugin-icons or a local .svelte
 * icon. Replaces Svelte 4's `ComponentType`, which no longer describes Svelte 5
 * components (they are functions, not classes).
 */
export type IconComponent = Component<{ class?: string }>;
