// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checksum } from "./Checksum";
import type { Gap } from "./Gap";
import type { MediaType } from "./MediaType";
import type { Quartet } from "./Quartet";
import type { ReadMode } from "./ReadMode";
import type { Ripper } from "./Ripper";
import type { Toc } from "./Toc";
import type { TrackEntry } from "./TrackEntry";

export interface ParsedLog { ripper: Ripper, ripper_version: string, language: string, read_offset: number | null, combined_rw_offset: number | null, drive: string, media_type: MediaType, accurate_stream: Quartet, defeat_audio_cache: Quartet, use_c2: Quartet, overread: Quartet, fill_silence: Quartet, delete_silence: Quartet, use_null_samples: Quartet, test_and_copy: Quartet, normalize: Quartet, read_mode: ReadMode, gap_handling: Gap, checksum: Checksum, toc: Toc, tracks: Array<TrackEntry>, id3_enabled: Quartet, }