// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ripper = "Exact Audio Copy" | "X Lossless Decoder" | "Whipper" | "CUERipper" | "dBpoweramp" | "Morituri" | "Abcde" | "Rip" | "Other";