// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Integrity } from "./Integrity";

export interface TestAndCopy { test_hash: string, copy_hash: string, test_skipzero_hash: string, copy_skipzero_hash: string, integrity: Integrity, integrity_skipzero: Integrity, }