// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TocHash } from "./TocHash";
import type { TocRaw } from "./TocRaw";

export interface Toc { raw: TocRaw, mbz: TocHash, ctdb_tocid: TocHash, gn: TocHash, mcdi: TocHash, }