// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TocEntry { track: number, start: string, length: string, start_sector: number, end_sector: number, }