// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TocEntry } from "./TocEntry";

export interface TocRaw { entries: Array<TocEntry>, lead_out: number, data_tracks: number, }