// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestAndCopy } from "./TestAndCopy";
import type { TrackError } from "./TrackError";

export interface TrackEntry { is_range: boolean, aborted: boolean, filename: string, peak_level: number | null, pregap_length: string | null, extraction_speed: number | null, gain: number | null, preemphasis: boolean | null, test_and_copy: TestAndCopy, errors: TrackError, }