// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackErrorRange } from "./TrackErrorRange";

export interface TrackErrorData { count: number, ranges: Array<TrackErrorRange>, }