// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackErrorData } from "./TrackErrorData";

export interface TrackError { read: TrackErrorData, skip: TrackErrorData, jitter_generic: TrackErrorData, jitter_edge: TrackErrorData, jitter_atom: TrackErrorData, drift: TrackErrorData, dropped: TrackErrorData, duplicated: TrackErrorData, [key: string]: TrackErrorData, }