// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccurateRipUnit } from "./AccurateRipUnit";
import type { TestAndCopy } from "./TestAndCopy";
import type { TrackError } from "./TrackError";

export interface TrackEntry { num: number, is_range: boolean, aborted: boolean, filenames: Array<string>, peak_level: number | null, pregap_length: string | null, extraction_speed: number | null, gain: number | null, preemphasis: boolean | null, test_and_copy: TestAndCopy, errors: TrackError, ar_info: Array<AccurateRipUnit>, }